run_dbca/easysubstrate - broken tsv when no hits are found
This (ugly patch) is needed because run_dbcan produces a broken
"dbcansub_hmm_results.tsv" file when no hits are found. The empty tsv
(again.. no hits) doesn't have all the corresponding headers. This
causes issues downstream as dbcan is ran in chunks and then merged (the
tsv with csvtk).

I've checked the following files:
- {prefix}_overview.tsv
- {prefix}_cgc_standard_out.tsv
- {prefix}_substrate_prediction.tsv
- {prefix}_dbcansub_hmm_results.tsv <- fixed with this patch

These other files contents look fine with no results (correct headers at
least).

BTW, this error only appears when the GFF summary is
executed:

```bash
process_dbcan_cazys \
      -hmm ERZ21784934_dbcan_sub_hmm.tsv.gz \
      -g ERZ21784934.gff.gz \
      -ov ERZ21784934_dbcan_overview.tsv.gz \
      -v 5.1.2-V1 \
      -o ERZ21784934_dbcan_cazys.gff

  gff_toolkit \
      -g ERZ21784934.gff.gz \
      -i ERZ21784934_interproscan.tsv.gz \
      -e ERZ21784934_emapper_annotations.tsv.gz \
      -s ERZ21784934_sanntis.gff.gz \
      --antismash ERZ21784934_antismash_concatenated.gff.gz \
      --dbcan-cazys ERZ21784934_dbcan_cazys.gff \
      -o ERZ21784934_annotation_summary.gff
  Traceback (most recent call last):
    File "/opt/conda/bin/process_dbcan_cazys", line 7, in
      sys.exit(main())
               ^^^^^^
    File
"/opt/conda/lib/python3.12/site-packages/mgnify_pipelines_toolkit/analysis/assembly/process_dbcan_result_cazys.py",
line 49, in main
      substrates = load_substrates(hmm_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
    File
"/opt/conda/lib/python3.12/site-packages/mgnify_pipelines_toolkit/analysis/assembly/process_dbcan_result_cazys.py",
line 165, in load_substrates
      substrate_idx = header_fields.index("Substrate")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ValueError: 'Substrate' is not in list
```

This happens because csvtk is concatenating the rows on all the chunk tsvs,
but the first one in this case doesn't have the correct columns (just a subset).